consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateHeroPayload:
    example:
      name: Voluptatem illum.
    properties:
      name:
        example: Voluptatem illum.
        type: string
    required:
    - name
    title: CreateHeroPayload
    type: object
  Hero:
    description: A comic hero (default view)
    example:
      id: 7.810761e+18
      name: Placeat excepturi perspiciatis veritatis.
    properties:
      id:
        description: Unique heroe ID
        example: 7.810761e+18
        format: int64
        type: integer
      name:
        description: Name of hero
        example: Placeat excepturi perspiciatis veritatis.
        type: string
    required:
    - id
    - name
    title: 'Mediatype identifier: application/vnd.hero+json; view=default'
    type: object
  HeroCollection:
    description: HeroCollection is the media type for an array of Hero (default view)
    example:
    - id: 7.810761e+18
      name: Placeat excepturi perspiciatis veritatis.
    - id: 7.810761e+18
      name: Placeat excepturi perspiciatis veritatis.
    items:
      $ref: '#/definitions/Hero'
    title: 'Mediatype identifier: application/vnd.hero+json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: A simple goa service
  title: Comics Heroes API
  version: ""
paths:
  /heroes:
    get:
      description: Retrieve all heroes
      operationId: hero#list
      produces:
      - application/vnd.hero+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HeroCollection'
      schemes:
      - http
      summary: list hero
      tags:
      - hero
    post:
      description: Create new hero
      operationId: hero#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateHeroPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: /hero/[0-9]+
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create hero
      tags:
      - hero
  /heroes/{heroID}:
    get:
      description: Get hero by id
      operationId: hero#show
      parameters:
      - description: Bottle ID
        in: path
        name: heroID
        required: true
        type: integer
      produces:
      - application/vnd.hero+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Hero'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show hero
      tags:
      - hero
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Hero'
schemes:
- http
swagger: "2.0"
