// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "comics": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/ottogiron/goa-heroes/design
// --out=$(GOPATH)/src/github.com/ottogiron/goa-heroes
// --version=v1.2.0

package app

import (
	"fmt"
	"strings"
)

// HeroHref returns the resource href.
func HeroHref(heroID interface{}) string {
	paramheroID := strings.TrimLeftFunc(fmt.Sprintf("%v", heroID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/heroes/%v", paramheroID)
}
