// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "comics": Application User Types
//
// Command:
// $ goagen
// --design=github.com/ottogiron/goa-heroes/design
// --out=$(GOPATH)/src/github.com/ottogiron/goa-heroes
// --version=v1.2.0

package app
